project:
  type: website
  output-dir: docs

website:
  title: "chelseaguo.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: 41625.qmd
        text: Final project

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

